Set the correct background color on SplashScreen's background
unoplatform/uno.resizetizer pull request #162
Opened 2023-07-31 23:34 UTC by pictos

GitHub Issue (If applicable): #156 

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

The icon background wasn't tinted with the backgroundColor set on `UnoSplashScreen`.

## What is the new behavior?

The icon's background is tinted with the color set on `UnoSplashScreen`.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

2023-08-04 00:12 UTC, nickrandolph commented on src/Resizetizer/src/SkiaSharpSvgTools.cs
> +				cvn.Clear(BackgroundColor.HasValue ? SKColors.Transparent : BackgroundColor.Value);
Why do we need to set the background color in the generated image. Isn't this set on the background of the page?

2023-08-04 01:11 UTC, pictos commented on src/Resizetizer/src/SkiaSharpSvgTools.cs
> +				cvn.Clear(BackgroundColor.HasValue ? SKColors.Transparent : BackgroundColor.Value);
This code runs for `UnoSplash, UnoImage and UnoIcon`, but think here... Would be better to run the background just for wasm and splashScreen. This is because of the way SplashScreen is built on wasm, on iOS we have a composition of controls, as you can see [here](https://github.com/unoplatform/uno.resizetizer/blob/main/src/Resizetizer/src/Resources/UnoSplash.storyboard#L27) the `color` component applies the backgroundColor, the same happens on android as you can see [here](https://github.com/unoplatform/uno.resizetizer/blob/main/src/Resizetizer/src/GenerateSplashAndroidResources.cs#L73-L77).
But on wasm, it's just an image on top of another one

2023-08-04 05:28 UTC, nickrandolph commented on src/Resizetizer/src/SkiaSharpSvgTools.cs
> +				cvn.Clear(BackgroundColor.HasValue ? SKColors.Transparent : BackgroundColor.Value);
For splash we do set the color on the background, so it shouldn't be required in the splash screen image - doing so will cause visual artifacts - in some scenarios you'll be able to see the edge of the image as it won't blend correctly with the background.

2023-08-07 12:42 UTC, dansiegel commented on src/Resizetizer/src/ResizetizeImages.cs
> +		public string[] InputsFile { get; set; }
Do we potentially need to track any Metadata about the files here? If so we should be using ITaskItem and not string.

2023-08-13 13:13 UTC, dansiegel approved these changes

2023-08-16 11:52 UTC, dansiegel requested changes

2023-08-16 11:52 UTC, dansiegel commented on src/Resizetizer/src/ResizetizeImages.cs
> +			}
Do not throw an exception here... you can Log a warning and return true. This should not break the build and you should NEVER throw an exception from an MSBuild Task

2023-08-18 13:45 UTC, dansiegel approved these changes

2023-08-21 19:02 UTC, pictos commented
> Have we confirmed these changes don't break if there's no uno splash screen defined?

@nickrandolph , yes

2023-08-23 13:37 UTC, nickrandolph commented on src/Resizetizer/src/GenerateWasmSplashAssets.cs
> +		if (UnoSplashScreen is { Length: 0 })
Is this true if UnoSplashScreen is null?

2023-09-21 15:52 UTC, nickrandolph approved these changes

2023-09-21 15:52 UTC, merged